import type { Metadata } from "next";
import LocalFont from "next/font/local";
import "./globals.css";
import { MainLayout } from "../components/main-layout";

const acumin = LocalFont({
  src: "../fonts/acumin_variable_concept.otf",
  variable: "--font-acumin",
});

const alternate = LocalFont({
  src: "../fonts/alternate_bold.ttf",
  variable: "--font-alternate",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased" suppressHydrationWarning>
      <body className="flex h-full bg-zinc-50">
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
